name: Build and test

on:
  push:
  pull_request:

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install
        run: |
          python -m venv .env
          source .env/bin/activate
          pip install maturin pytest
      - name: Build
        run: |
          source .env/bin/activate
          maturin develop
      - name: Test
        run: |
          source .env/bin/activate
          pytest .
